apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  SECRET_KEY: c2VjcmV0a2V5MTIzNDU=  # base64 de 'secretkey12345'
  DB_NAME: ZWR1Y2F0aW9u  # base64 de 'education'
  DB_USER: ZWR1c2Vy  # base64 de 'eduser'
  DB_PASSWORD: cGFzc3dvcmQxMjM=  # base64 de 'password123'
  DB_HOST: bXlkYg==  # base64 de 'mydb'
  DB_PORT: NTQzMg==  # base64 de '5432'
